# Generated by Django 2.2.3 on 2020-04-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('er_no', models.IntegerField(primary_key=True, serialize=False)),
                ('rfid_no', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField()),
                ('dept', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('sub_code', models.IntegerField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_ids', models.ManyToManyField(to='attendance.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_time', models.CharField(max_length=16)),
                ('attendance_date', models.CharField(max_length=12)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
                ('Subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Subject')),
                ('Teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Teacher')),
            ],
        ),
    ]
