# Generated by Django 2.2.3 on 2020-04-09 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_teacher_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='dept',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
